### ISSUE TITLE
Question - new eslint.CLIEngine(config)

### ISSUE THREAD

**Issue by sarbbottam** [kentcdodds/eslint-find-new-rules#16]
Hi @kentcdodds, @ta2edchimp,

Please pardon my ignorance and limited knowledge about `eslint`, got curios about the `plugin` support and have been looking into the code. I could not comprehend the following code w.r.t to the [documentation](http://eslint.org/docs/1.0.0/developer-guide/nodejs-api#cliengine)

`configFile` - The configuration file to use (default: null). Corresponds to `-c`
`useEslintrc` - Set to false to disable use of `.eslintrc` files (default: true). Corresponds to `--no-eslintrc`.

``` js
  var cliEngine = new eslint.CLIEngine({
    // ignore any config applicable depending on the location on the filesystem
    useEslintrc: false,
    // point to the particular config
    configFile: file,
  })
```
- Why do we need to pass `configFile` option? The test results are not impacted if I comment/remove `configFile: file,` 
- Why are we disabling `.eslintrc`? What if the user is using `.eslintrc` or `package.json` for the existing rules.

Thanks!

**Comment by ta2edchimp** [comment]
`configFile` - Loads (and "compiles", based on configs to extend) the specified config, containing a comprehensive collection of all rules applicable.
`useEslintrc` - Set to false because we **only** want those rules from the specified config file, but nothing else. A possible side effect from setting this to true could result in a rule set being aggregated using configurations all the way up from a given location to the user's home dir.

The following statement, invoking `getConfigForFile()`, just uses the config file as a dummy, for us to retrieve the desired config object. Based on the specified location on the filesystem, eslint configs could be taken into account, that have absolutely nothing to do with what we want to look up (therefore, `useEslintrc: false`).
- What do you mean by "the test results are not impacted"? Those from `/test/bin.js`?
- If a particular `.eslintrc*` or package.json's `eslintConfig` property is to be tested, it will be given via `configFile`.

**Comment by sarbbottam** [comment]
Thanks, I am clear about the `useEslintrc`. I guess, I got confused, as the `test/fixture/.eslintrc` got renamed to `test/fixture/.eslintrc.js` 

> > What do you mean by "the test results are not impacted"? Those from /test/bin.js?

Yes, there is no test failure if I remove, `configFile: file` for the config object passed to `eslint.CLIEngine`.

To be precise, I don't yet understand the purpose of passing the `same file`, once during `instantiation` and then in `getConfigForFile`.

**Comment by ta2edchimp** [comment]
Passing the same file twice is just a workaround to get the desired result:
Passing it as a property of `CLIEngine`'s constructor is mandatory for our use case, it lets ESLint actually load and compose the config (this is the first half of the functionality we desire). But `getConfigForFile()` is the method returning this config back to us (the second half, actually receiving the desired object).
By reusing the same file path twice, we workaround the requirement of `getConfigForFile` to get called with an existing file as argument without having to fiddle around with temp files on the filesystem or doing any mocking (as we do in the tests).
We have to do it this way, because ESLint's internal `Config` class is not exposed via its API, but is used by `getConfigForFile()`.

---

As for the tests, I think we've got a logical mistake in `/test/bin.js` the way the mock the return values of `./index.js`'s function. It will **always** return the local scope's `rules` array, regardless of the actual rules detected by the functionality within `./bin.js`.
I think, the way it is now, the tests will always pass, as long as there's no exception thrown :(

**Comment by sarbbottam** [comment]
Thanks @ta2edchimp for the detailed explanation. Please excuse me for bothering with trivial queries.

> > Passing the same file twice is just a workaround to get the desired result:

I have been fiddling around with `CLIEngine` for clarifying my concerns and I guess passing the `filePath` to `getConfigForFile` can be omitted. 

Could you please take a look at [index.js](https://github.com/sarbbottam/eslint-cli-engine/blob/master/index.js) and [index.test.js](https://github.com/sarbbottam/eslint-cli-engine/blob/master/index.test.js). 

I am not passing any file name to `getConfigForFile`, but still getting the desired result.

---

``` js
// .eslintrc
{
  "extends": "./.eslint.json",
  "rules": {
    "space-before-function-paren": [2, "never"],
    "space-before-blocks": [2, "always"],
    "no-debugger":0
  }
}
```

```
// eslint.json 
{
  "extends": "./.eslint.yml",
  "rules": {
    "semi": [2, "always"],
    "quotes": [2, "single"],
    "no-multi-str": 0
  }
}
```

```
// .eslint.yml
rules:
  no-console:
    - 2
  no-alert:
    - 2
```

---

```
// output of getConfigForFile()
{
  'no-console': [ 2 ],
  'no-alert': [ 2 ],
  semi: [ 2, 'always' ],
  quotes: [ 2, 'single' ],
  'no-multi-str': 0,
  'space-before-function-paren': [ 2, 'never' ],
  'space-before-blocks': [ 2, 'always' ],
  'no-debugger': 0
}
```

**Comment by ta2edchimp** [comment]
You're absolutely right; when omitted, the core functionality that we're interested in (ESLint's [`Config.getConfig()`](https://github.com/eslint/eslint/blob/master/lib/config.js#L199-L270)), has a [built in fallback to the process' cwd](https://github.com/eslint/eslint/blob/master/lib/config.js#L209) ... So I assume we can get rid of this lousy workaround, that passing the config file as an argument is.

**Comment by sarbbottam** [comment]
I guess, I am comprehending eslint much better now, Thank you

**Comment by sarbbottam** [comment]
This has been taken care in #18 at [`return cliEngine.getConfigForFile()`](https://github.com/kentcdodds/eslint-find-new-rules/pull/18/files#diff-eab9f83cad8197d50eb520415a2442dfR34.)
